import 'package:hive/hive.dart';
part 'language.g.dart';

@HiveType(typeId: 8)
class Language {
  @HiveField(0)
  int? id;
  @HiveField(1)
  String? code;
  @HiveField(2)
  String? display;
  @HiveField(3)
  int? isDefault;
  @HiveField(4)
  bool? isActive;
  @HiveField(5)
  int? isAutoGenerated;
  @HiveField(6)
  String? createdAt;
  @HiveField(7)
  String? updatedAt;
  @HiveField(8)
  String? type;

  Language({
    this.id,
    this.code,
    this.display,
    this.isDefault,
    this.isActive,
    this.isAutoGenerated,
    this.createdAt,
    this.updatedAt,
    this.type,
  });
}


Language mapJsonToLanguage(Map<String, dynamic> languageMap) {
  return Language(
    id: languageMap['id'],
    code: languageMap['code'],
    display: languageMap['display'],
    isDefault: languageMap['isDefault'],
    isActive: languageMap['isActive'],
    isAutoGenerated: languageMap['isAutoGenerated'],
    createdAt: languageMap['createdAt'],
    updatedAt: languageMap['updatedAt'],
    type: languageMap['type'],
  );
}

